codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_not_found: success
        if_ci_failed: error

    patch:
      default:
        target: auto
        threshold: 1%
        if_not_found: success

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false

# Exclude test infrastructure and e2e setup files from coverage
# These are not part of the public library API
ignore:
  - "src/e2e/**"
  - "src/testing/cli-helpers.ts"
  - "src/testing/conversation-fixtures.ts"
